server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false  # Disable Config Server for local development
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        # Auth Service Route
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
        
        # Log Collector Route
        - id: log-collector-service
          uri: lb://LOG-COLLECTOR-SERVICE
          predicates:
            - Path=/api/logs/**
          filters:
            - AuthenticationFilter
        
        # Anomaly Detector Route
        - id: anomaly-detector-service
          uri: lb://ANOMALY-DETECTOR-SERVICE
          predicates:
            - Path=/api/anomaly/**
          filters:
            - AuthenticationFilter
        
        # Alert Manager Route
        - id: alert-manager-service
          uri: lb://ALERT-MANAGER-SERVICE
          predicates:
            - Path=/api/alerts/**
          filters:
            - AuthenticationFilter
        
        # Notification Service Route
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**
          filters:
            - AuthenticationFilter
        
        # Incident Tracker Route
        - id: incident-tracker-service
          uri: lb://INCIDENT-TRACKER-SERVICE
          predicates:
            - Path=/api/incidents/**
          filters:
            - AuthenticationFilter
        
        # Dashboard Service Route
        - id: dashboard-service
          uri: lb://DASHBOARD-SERVICE
          predicates:
            - Path=/api/dashboard/**
          filters:
            - AuthenticationFilter
        
        # WebSocket Route for Dashboard
        - id: dashboard-ws
          uri: lb:ws://DASHBOARD-SERVICE
          predicates:
            - Path=/ws/**
          filters:
            - AuthenticationFilter
      
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:mySecretKey12345678901234567890}
  expiration: 86400000  # 24 hours

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client: TRACE 