apiVersion: v2
name: incident-platform
description: AI-Driven Incident Detection & Response System
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - incident-management
  - ai
  - microservices
  - monitoring
home: https://github.com/atakanzaa/incident-platform
sources:
  - https://github.com/atakanzaa/incident-platform
  - https://github.com/atakanzaa/incident-platform-config
maintainers:
  - name: Platform Team
    email: atakanzaa@users.noreply.github.com
dependencies:
  - name: postgresql
    version: 12.12.10
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: mongodb
    version: 13.18.5
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
  - name: kafka
    version: 25.3.5
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
  - name: rabbitmq
    version: 12.5.6
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: redis
    version: 18.1.5
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: prometheus
    version: 25.3.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: 7.0.11
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled 