apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: incident-platform-development
  namespace: argocd
  labels:
    app: incident-platform
    env: development
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/atakanzaa/incident-platform-config.git
    targetRevision: development
    path: environments/development
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: incident-platform-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 3s
        factor: 2
        maxDuration: 1m
  revisionHistoryLimit: 5
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/ports/*/nodePort
  info:
    - name: Description
      value: "Incident Platform Development Environment"
    - name: Repository
      value: "https://github.com/atakanzaa/incident-platform-config.git"
    - name: Branch
      value: "development"
    - name: Contact
      value: "development-team@company.com" 