apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: incident-platform-prod
  namespace: argocd
  labels:
    app: incident-platform
    env: production
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: production-alerts
    notifications.argoproj.io/subscribe.on-sync-failed.slack: production-alerts
    notifications.argoproj.io/subscribe.on-health-degraded.slack: production-alerts
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/atakanzaa/incident-platform-config.git
    targetRevision: main
    path: environments/production
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: global.environment
          value: production
  destination:
    server: https://kubernetes.default.svc
    namespace: incident-platform-prod
  syncPolicy:
    # Manual sync for production - requires approval
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  revisionHistoryLimit: 20
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      jsonPointers:
        - /spec/replicas
        - /status
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
  operation:
    sync:
      syncOptions:
        - Validate=true
        - PrunePropagationPolicy=foreground
        - RespectIgnoreDifferences=true
  info:
    - name: Description
      value: "Incident Platform Production Environment"
    - name: Repository
      value: "https://github.com/atakanzaa/incident-platform-config.git"
    - name: Branch
      value: "main"
    - name: Contact
      value: "production-team@company.com"
    - name: Approval Required
      value: "Yes - Manual deployment only"
    - name: Backup Schedule
      value: "Daily at 2 AM UTC" 